spring:
    application:
        name: KafkaStream

kafka:
    bootstrap-servers: localhost:9092

server:
    port: 8083

kafkastreams:
    id: KafkaStream
    paymentInboundTopic: "transaction"
    railsFooOutboundTopic : "rails-foo-topic"
    railsBarOutboundTopic : "rails-bar-topic"